### ISSUE TITLE
Support for Haddock 2.15

### ISSUE THREAD

**Issue by peti** [ivan-m/haskell-docs#14]
We've updated to Haddock 2.15 in NixOS, but unfortunately that change breaks the build of this package. Could you maybe extend the Cabal file to support the latest version?

**Comment by cjmazey** [comment]
I have the same issue. . .the above doesn't work.

**Comment by Saedeas** [comment]
I have a similar issue.  When I tried changing the code as recommended I get an error that says

"InstallPlan: internal error: configured package depends on a non-library package"

After cabal says it has installed Haddock.  When I then check the info for haddock, it says

Versions installed: [ Unknown ]

I assume these have something to do with one another, but I'm not that familiar with Cabal.

**Comment by ivan-m** [comment]
I think this can be closed.

**Comment by evanmeng** [comment]
This shouldn't be closed since such error still occurs with newest GHC, Cabal and Haddock.

**Comment by ivan-m** [comment]
Except @chrisdone already accepted my pull request to add such support in.

Though he still has to release it on Hackage...

**Comment by mazen-mardini** [comment]
I'm having the same problem. I'd also like to see the fix being added to Hackage.

**Comment by ivan-m** [comment]
@chrisdone Is this closed by #29?

**Comment by ivan-m** [comment]
I believe this is done.
