### ISSUE TITLE
haskell-docs-4.2.5 conflicts with descriptive-0.9.3

### ISSUE THREAD

**Issue by welf** [ivan-m/haskell-docs#22]
I used [your manual](https://github.com/chrisdone/emacs-haskell-config) to customize Emacs. Package _descriptive-0.9.3_ was installed as dependency to _hindent_. 

http://lpaste.net/127029

**Comment by ivan-m** [comment]
This doesn't appear to be a conflict per-se; my guess is that a dependency somewhere wants an older version of aeson/mtl.

Maybe also run the same command with `-v3` to get more information as to why older versions of mtl and aeson are chosen?

**Comment by ivan-m** [comment]
Is this still a problem?

**Comment by ivan-m** [comment]
As it's been almost two years without any responses I'm closing this; please re-open if this is still a problem.
