### ISSUE TITLE
haskell-docs 4.2.6 not building with GHC 7.8.4

### ISSUE THREAD

**Issue by iarekk** [ivan-m/haskell-docs#30]
Apparently **haddock-library** needs to be included for GHC 7.8.4 as well as for GHC 7.10. When building **4.2.6** I get the message below while **4.2.5** builds fine.

    src/haddock-api/Haskell/Docs/HaddockDoc.hs:14:18:
        Could not find module ‘Documentation.Haddock.Types’
        It is a member of the hidden package ‘haddock-library-1.1.1’.
        Perhaps you need to add ‘haddock-library’ to the build-depends in your .cabal file.

**Comment by Lacaranian** [comment]
Seeing the same thing on my end, worth looking into.

**Comment by ivan-m** [comment]
I believe this should now be fixed.
