### ISSUE TITLE
Plans to support ghc-7.10 and 8.x?

### ISSUE THREAD

**Issue by benjaminfjones** [ivan-m/haskell-docs#34]
Are there plans to support the last to major releases of GHC? I've tried building with ghc-8.0.2-rc2 and `haddock-api` fails to build.

**Comment by ivan-m** [comment]
Well, it already does build with 7.10 and 8.0.1, doesn't it?

I'd forgotten that I had already installed 8.0.2 and thus could check if this builds with it.

**Comment by benjaminfjones** [comment]
You're right, it does build now that I try it again. Sorry for the noise!
